apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskerino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskerino
  template:
    metadata:
      labels:
        app: flaskerino
    spec:
      containers:
        - name: flaskerino
          image: IMAGE_REPLACE
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flaskerino-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: flaskerino
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

